channels:
  - conda-forge
dependencies:
  - conda-forge::ipython>=7
  - conda-forge::ipywidgets>=7
  - conda-forge::paramiko>=2.5
  - conda-forge::python>=3.6
  - conda-forge::tqdm>=4
  # test
  - conda-forge::flake8<5
  - conda-forge::flake8-builtins
  - conda-forge::flake8-comprehensions
  - conda-forge::flake8-import-order
  - conda-forge::flake8-mutable
  - conda-forge::flake8-quotes
  - conda-forge::pep8-naming
  - conda-forge::pytest
  - conda-forge::pytest-flake8
  # pip
  - conda-forge::pip
  - pip:
    - --editable .
