channels:
  - conda-forge
  - defaults
dependencies:
  - ipython>=7
  - ipywidgets>=7
  - paramiko>=2.5
  - python>=3.6
  - tqdm>=4
  # test
  - flake8<5
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-mutable
  - flake8-quotes
  - pep8-naming
  - pytest
  - pytest-flake8
  # pip
  - pip
  - pip:
    - --editable .
