channels:
  - conda-forge
dependencies:
  - conda-forge::ipython>=7
  - conda-forge::paramiko>=2.5
  - conda-forge::python>=3.6
  - conda-forge::tqdm>=4
  # optional
  - conda-forge::ipywidgets>=7
  # test
  - conda-forge::flake8
  - conda-forge::flake8-bugbear
  - conda-forge::flake8-builtins
  - conda-forge::flake8-comprehensions
  - conda-forge::flake8-docstrings
  - conda-forge::flake8-import-order
  - conda-forge::flake8-mutable
  - conda-forge::flake8-pyproject
  - conda-forge::flake8-quotes
  - conda-forge::flake8-use-fstring
  - conda-forge::flake8-use-pathlib
  - conda-forge::pep8-naming
  # pip
  - conda-forge::pip
  - pip:
    - --editable .
