name: CI

on: [push]

jobs:

  build:
    name: build (${{ matrix.os }}, python-${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
      - run: conda env create --force --name test
      - run: conda run --name test --no-capture-output flake8
